---
title: Generate list of ACS Samples
author: Miguel Rodo
---

```{r , include = FALSE}
knitr::opts_chunk$set(echo = FALSE)
```
  
Save `data_tidy_clinical.rds` from `TuberculomicsCompendium` if it is not available. This is the full clinical data set for the ACS, including all variables.
```{r }
dir_output <- projr::projr_dir_get("output")
load(projr::projr_path_get("data-raw", "data_tidy_clinical.rda"))
```

However, you only need the names of progressors and matched controls. I've also included whether or not they progressed.

```{r }
data_tidy_acs_participants <- data_tidy_clinical |>
  dplyr::filter(
    ProgressorOrControl == "yes"
  ) |>
  dplyr::select(
    SubjectID, Progressor) |>
  dplyr::group_by(SubjectID) |>
    dplyr::slice(1) |>
    dplyr::ungroup()

usethis::use_data(data_tidy_acs_participants, overwrite = TRUE)

file.copy(
  "data/data_tidy_acs_participants.rda",
  file.path(dir_output, "data_tidy_acs_participants.rda"),
)
file.copy(
  "data/data_tidy_clinical.rda",
  file.path(dir_output, "data_tidy_clinical.rda"),
)
readr::write_csv(
  data_tidy_acs_participants,
  file = file.path(dir_output, "data_tidy_acs_participants.csv")
)
readr::write_csv(
  data_tidy_clinical,
  file = file.path(dir_output, "data_tidy_clinical.csv")
)
```
