---
title: Generate list of ACS Samples
author: Miguel Rodo
---

```{r , include = FALSE}
knitr::opts_chunk$set(echo = FALSE)
setwd(here::here())
```
  
Save `data_tidy_clinical.rds` from `TuberculomicsCompendium` if it is not available. This is the full clinical data set for the ACS, including all variables.
```{r }
dir_output <- here::here("../Output/OutputDataTidyACSClinical")
if (!dir.exists(dir_output)) dir.create(dir_output, recursive = TRUE)
if (!file.exists(here::here("data/data_tidy_clinical.rda"))) {
  #if (!requireNamespace("TuberculomicsCompendium", quietly = TRUE)) {
  stop("Email Miguel Rodo at rdxmig002@myuct.ac.za for the TuberculomicsCompendium package")
  #}
  #data("clinical_data", package = "TuberculomicsCompendium")
  #data_tidy_clinical <- clinical_data
  #rm("clinical_data")
  #usethis::use_data(data_tidy_clinical)
  #readr::write_csv(
  #  data_tidy_clinical,
  #  file = file.path(dir_output, "data_tidy_clinical.csv")
  #)
  #invisible(file.copy(
  #  from = "data/data_tidy_clinical.rda",
  #  to = file.path(dir_output, "data_tidy_clinical.rda")
  #))
}
load(here::here("data/data_tidy_clinical.rda"))
```

However, you only need the names of progressors and matched controls. I've also included whether or not they progressed.

```{r }
data_tidy_acs_participants <- data_tidy_clinical |>
  dplyr::filter(
    ProgressorOrControl == "yes"
  ) |>
  dplyr::select(
    SubjectID, Progressor) |>
  dplyr::group_by(SubjectID) |>
    dplyr::slice(1) |>
    dplyr::ungroup()
usethis::use_data(data_tidy_acs_participants, overwrite = TRUE)
if (!requireNamespace("readr", quietly = TRUE)) {
  utils::install.packages("readr", quiet = TRUE)
}

readr::write_csv(
  data_tidy_acs_participants,
  file = file.path(dir_output, "data_tidy_acs_participants.csv")
)
unlink(file.path(dir_output, "data_tidy_acs_participants.rda"))
invisible(file.copy(
  from = "data/data_tidy_acs_participants.rda",
  to = file.path(dir_output, "data_tidy_acs_participants.rda")
))
```